name: CI

on: [push, pull_request]

jobs:

  bashate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: bashate
        env:
          CI: true
          COMMIT_SHA: ${{ github.sha }}
        run: |
          while IFS= read -r line; do echo "Linting ${line}"; docker run --rm -v "${PWD}:${PWD}" textclean/bashate -i E006 "${PWD}/${line}" || exit 1; done < <(git ls-files '*.sh')

  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: markdownlint
        env:
          CI: true
          COMMIT_SHA: ${{ github.sha }}
        run: |
          echo '{"default": true,"line_length": false,"no-inline-html": false,"first-line-h1": false}' > .markdownlint.json
          while IFS= read -r line; do echo "Linting ${line}"; docker run --rm -v "${PWD}:/markdown" -v "${PWD}:${PWD}" 06kellyjac/markdownlint-cli "${PWD}/${line}" || exit 1; done < <(git ls-files '*.md')

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: shellcheck
        env:
          CI: true
          COMMIT_SHA: ${{ github.sha }}
        run: |
          while IFS= read -r line; do echo "Linting ${line}"; docker run --rm -v "${PWD}:${PWD}" koalaman/shellcheck -x "${PWD}/${line}" || exit 1; done < <(git ls-files '*.sh')

  shfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: shfmt
        env:
          CI: true
          COMMIT_SHA: ${{ github.sha }}
        run: |
          while IFS= read -r line; do echo "Linting ${line}"; docker run --rm -v "${PWD}:${PWD}" mvdan/shfmt -s -i 4 -ci -sr -d "${PWD}/${line}" || exit 1; done < <(git ls-files '*.sh')

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: yamllint
        env:
          CI: true
          COMMIT_SHA: ${{ github.sha }}
        run: |
          while IFS= read -r line; do echo "Linting ${line}"; docker run --rm -v "${PWD}:${PWD}" sdesbure/yamllint yamllint -d '{extends: default, rules: {document-start: {present: false}, line-length: disable}}' "${PWD}/${line}" || exit 1; done < <(git ls-files '*.yaml' '*.yml')

  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]
    steps:
      - uses: actions/checkout@v1
      - name: run
        env:
          CI: true
          COMMIT_SHA: ${{ github.sha }}
        run: |
          while IFS= read -r line; do echo; sudo -E bash ./main.sh -vt "${line}" || exit 1; echo; done < <(git ls-files '.scripts/*.sh' | sed -E 's/^\.scripts\/(\w+)\.sh$/\1/')
